# Configuración mínima de tu Jupyter Book
title: "Trabajo Final HDTC - Titanic"
author: "Equipo"
logo: ""  # opcional, puedes poner ruta a un logo
language: es
execute:
  execute_notebooks: off
  timeout: 60
